Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\AuthenticatedSessionController",
            "name": "AuthenticatedSessionController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-AuthenticatedSessionController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\AuthenticatedSessionController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Display\u0020the\u0020login\u0020view.",
            "url": "classes/App-Http-Controllers-Auth-AuthenticatedSessionController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\AuthenticatedSessionController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Handle\u0020an\u0020incoming\u0020authentication\u0020request.",
            "url": "classes/App-Http-Controllers-Auth-AuthenticatedSessionController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\AuthenticatedSessionController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Destroy\u0020an\u0020authenticated\u0020session.",
            "url": "classes/App-Http-Controllers-Auth-AuthenticatedSessionController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\ConfirmablePasswordController",
            "name": "ConfirmablePasswordController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-ConfirmablePasswordController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\ConfirmablePasswordController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Show\u0020the\u0020confirm\u0020password\u0020view.",
            "url": "classes/App-Http-Controllers-Auth-ConfirmablePasswordController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\ConfirmablePasswordController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Confirm\u0020the\u0020user\u0027s\u0020password.",
            "url": "classes/App-Http-Controllers-Auth-ConfirmablePasswordController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\EmailVerificationNotificationController",
            "name": "EmailVerificationNotificationController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-EmailVerificationNotificationController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\EmailVerificationNotificationController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Send\u0020a\u0020new\u0020email\u0020verification\u0020notification.",
            "url": "classes/App-Http-Controllers-Auth-EmailVerificationNotificationController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\EmailVerificationPromptController",
            "name": "EmailVerificationPromptController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-EmailVerificationPromptController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\EmailVerificationPromptController\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Display\u0020the\u0020email\u0020verification\u0020prompt.",
            "url": "classes/App-Http-Controllers-Auth-EmailVerificationPromptController.html#method___invoke"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\NewPasswordController",
            "name": "NewPasswordController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-NewPasswordController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\NewPasswordController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Display\u0020the\u0020password\u0020reset\u0020view.",
            "url": "classes/App-Http-Controllers-Auth-NewPasswordController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\NewPasswordController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Handle\u0020an\u0020incoming\u0020new\u0020password\u0020request.",
            "url": "classes/App-Http-Controllers-Auth-NewPasswordController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\PasswordController",
            "name": "PasswordController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-PasswordController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\PasswordController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020the\u0020user\u0027s\u0020password.",
            "url": "classes/App-Http-Controllers-Auth-PasswordController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\PasswordResetLinkController",
            "name": "PasswordResetLinkController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-PasswordResetLinkController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\PasswordResetLinkController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Display\u0020the\u0020password\u0020reset\u0020link\u0020request\u0020view.",
            "url": "classes/App-Http-Controllers-Auth-PasswordResetLinkController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\PasswordResetLinkController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Handle\u0020an\u0020incoming\u0020password\u0020reset\u0020link\u0020request.",
            "url": "classes/App-Http-Controllers-Auth-PasswordResetLinkController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\RegisteredUserController",
            "name": "RegisteredUserController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-RegisteredUserController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\RegisteredUserController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Display\u0020the\u0020registration\u0020view.",
            "url": "classes/App-Http-Controllers-Auth-RegisteredUserController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\RegisteredUserController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Handle\u0020an\u0020incoming\u0020registration\u0020request.",
            "url": "classes/App-Http-Controllers-Auth-RegisteredUserController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\VerifyEmailController",
            "name": "VerifyEmailController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-VerifyEmailController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\VerifyEmailController\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Mark\u0020the\u0020authenticated\u0020user\u0027s\u0020email\u0020address\u0020as\u0020verified.",
            "url": "classes/App-Http-Controllers-Auth-VerifyEmailController.html#method___invoke"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CollectionGameController",
            "name": "CollectionGameController",
            "summary": "Contr\u00F4leur\u0020pour\u0020g\u00E9rer\u0020les\u0020jeux\u0020dans\u0020la\u0020collection\u0020d\u0027un\u0020utilisateur.",
            "url": "classes/App-Http-Controllers-CollectionGameController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CollectionGameController\u003A\u003Aadd_to_collection\u0028\u0029",
            "name": "add_to_collection",
            "summary": "Ajoute\u0020un\u0020jeu\u0020dans\u0020la\u0020collection\u0020de\u0020l\u0027utilisateur.",
            "url": "classes/App-Http-Controllers-CollectionGameController.html#method_add_to_collection"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CollectionGameController\u003A\u003Acollection_jeux\u0028\u0029",
            "name": "collection_jeux",
            "summary": "Affiche\u0020les\u0020jeux\u0020de\u0020la\u0020collection\u0020de\u0020l\u0027utilisateur\u0020avec\u0020des\u0020filtres\u0020optionnels.",
            "url": "classes/App-Http-Controllers-CollectionGameController.html#method_collection_jeux"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CollectionGameController\u003A\u003Aedit_collection_jeu\u0028\u0029",
            "name": "edit_collection_jeu",
            "summary": "Affiche\u0020le\u0020formulaire\u0020pour\u0020\u00E9diter\u0020la\u0020note,\u0020le\u0020commentaire\u0020et\u0020la\u0020progression\u0020d\u0027un\u0020jeu.",
            "url": "classes/App-Http-Controllers-CollectionGameController.html#method_edit_collection_jeu"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CollectionGameController\u003A\u003Aupdate_collection_jeu\u0028\u0029",
            "name": "update_collection_jeu",
            "summary": "Met\u0020\u00E0\u0020jour\u0020les\u0020informations\u0020d\u0027un\u0020jeu\u0020dans\u0020la\u0020collection\u0020de\u0020l\u0027utilisateur\u0020\u0028note,\u0020commentaire,\u0020progression\u0029.",
            "url": "classes/App-Http-Controllers-CollectionGameController.html#method_update_collection_jeu"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CollectionGameController\u003A\u003Adelete_collection_jeu\u0028\u0029",
            "name": "delete_collection_jeu",
            "summary": "Supprime\u0020un\u0020jeu\u0020de\u0020la\u0020collection\u0020de\u0020l\u0027utilisateur.",
            "url": "classes/App-Http-Controllers-CollectionGameController.html#method_delete_collection_jeu"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CollectionSupportController",
            "name": "CollectionSupportController",
            "summary": "Contr\u00F4leur\u0020pour\u0020g\u00E9rer\u0020les\u0020actions\u0020sur\u0020la\u0020collection\u0020de\u0020supports\u0020d\u0027un\u0020utilisateur.",
            "url": "classes/App-Http-Controllers-CollectionSupportController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CollectionSupportController\u003A\u003Aadd_to_collection\u0028\u0029",
            "name": "add_to_collection",
            "summary": "Ajoute\u0020un\u0020support\u0020\u00E0\u0020la\u0020collection\u0020de\u0020l\u0027utilisateur.",
            "url": "classes/App-Http-Controllers-CollectionSupportController.html#method_add_to_collection"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CollectionSupportController\u003A\u003Acollection_supports\u0028\u0029",
            "name": "collection_supports",
            "summary": "Affiche\u0020les\u0020supports\u0020dans\u0020la\u0020collection\u0020d\u0027un\u0020utilisateur.",
            "url": "classes/App-Http-Controllers-CollectionSupportController.html#method_collection_supports"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CollectionSupportController\u003A\u003Aedit_collection_support\u0028\u0029",
            "name": "edit_collection_support",
            "summary": "Affiche\u0020la\u0020page\u0020d\u0027\u00E9dition\u0020du\u0020commentaire\u0020d\u0027un\u0020support\u0020dans\u0020la\u0020collection.",
            "url": "classes/App-Http-Controllers-CollectionSupportController.html#method_edit_collection_support"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CollectionSupportController\u003A\u003Aupdate_collection_support\u0028\u0029",
            "name": "update_collection_support",
            "summary": "Met\u0020\u00E0\u0020jour\u0020le\u0020commentaire\u0020d\u0027un\u0020support\u0020dans\u0020la\u0020collection\u0020de\u0020l\u0027utilisateur.",
            "url": "classes/App-Http-Controllers-CollectionSupportController.html#method_update_collection_support"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CollectionSupportController\u003A\u003Adelete_collection_support\u0028\u0029",
            "name": "delete_collection_support",
            "summary": "Supprime\u0020un\u0020support\u0020de\u0020la\u0020collection\u0020de\u0020l\u0027utilisateur.",
            "url": "classes/App-Http-Controllers-CollectionSupportController.html#method_delete_collection_support"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "classes/App-Http-Controllers-Controller.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\GameController",
            "name": "GameController",
            "summary": "Contr\u00F4leur\u0020pour\u0020la\u0020gestion\u0020des\u0020jeux.",
            "url": "classes/App-Http-Controllers-GameController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\GameController\u003A\u003Aliste_jeux\u0028\u0029",
            "name": "liste_jeux",
            "summary": "R\u00E9cup\u00E8re\u0020et\u0020affiche\u0020la\u0020liste\u0020des\u0020jeux\u0020avec\u0020les\u0020filtres.",
            "url": "classes/App-Http-Controllers-GameController.html#method_liste_jeux"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\GameController\u003A\u003Adetail_jeu\u0028\u0029",
            "name": "detail_jeu",
            "summary": "R\u00E9cup\u00E8re\u0020et\u0020affiche\u0020les\u0020d\u00E9tails\u0020d\u0027un\u0020jeu\u0020s\u00E9lectionn\u00E9.",
            "url": "classes/App-Http-Controllers-GameController.html#method_detail_jeu"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProfileController",
            "name": "ProfileController",
            "summary": "",
            "url": "classes/App-Http-Controllers-ProfileController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProfileController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Display\u0020the\u0020user\u0027s\u0020profile\u0020form.",
            "url": "classes/App-Http-Controllers-ProfileController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProfileController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020the\u0020user\u0027s\u0020profile\u0020information.",
            "url": "classes/App-Http-Controllers-ProfileController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ProfileController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Delete\u0020the\u0020user\u0027s\u0020account.",
            "url": "classes/App-Http-Controllers-ProfileController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SupportController",
            "name": "SupportController",
            "summary": "Contr\u00F4leur\u0020pour\u0020la\u0020gestion\u0020des\u0020supports.",
            "url": "classes/App-Http-Controllers-SupportController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SupportController\u003A\u003Aliste_supports\u0028\u0029",
            "name": "liste_supports",
            "summary": "R\u00E9cup\u00E8re\u0020et\u0020affiche\u0020la\u0020liste\u0020des\u0020supports\u0020avec\u0020les\u0020filtres.",
            "url": "classes/App-Http-Controllers-SupportController.html#method_liste_supports"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SupportController\u003A\u003Adetail_support\u0028\u0029",
            "name": "detail_support",
            "summary": "R\u00E9cup\u00E8re\u0020et\u0020affiche\u0020les\u0020d\u00E9tails\u0020d\u0027un\u0020support\u0020s\u00E9lectionn\u00E9.",
            "url": "classes/App-Http-Controllers-SupportController.html#method_detail_support"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UserController",
            "name": "UserController",
            "summary": "Contr\u00F4leur\u0020pour\u0020la\u0020gestion\u0020des\u0020utilisateurs.",
            "url": "classes/App-Http-Controllers-UserController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UserController\u003A\u003Aprofil\u0028\u0029",
            "name": "profil",
            "summary": "Affiche\u0020le\u0020profil\u0020d\u0027un\u0020utilisateur.",
            "url": "classes/App-Http-Controllers-UserController.html#method_profil"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UserController\u003A\u003Aliste_utilisateurs_admin\u0028\u0029",
            "name": "liste_utilisateurs_admin",
            "summary": "Affiche\u0020la\u0020liste\u0020des\u0020utilisateurs\u0020pour\u0020l\u0027administrateur.",
            "url": "classes/App-Http-Controllers-UserController.html#method_liste_utilisateurs_admin"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UserController\u003A\u003Aliste_utilisateurs\u0028\u0029",
            "name": "liste_utilisateurs",
            "summary": "Affiche\u0020la\u0020liste\u0020des\u0020utilisateurs\u0020publics.",
            "url": "classes/App-Http-Controllers-UserController.html#method_liste_utilisateurs"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UserController\u003A\u003Aedit_utilisateur\u0028\u0029",
            "name": "edit_utilisateur",
            "summary": "Affiche\u0020le\u0020formulaire\u0020de\u0020modification\u0020d\u0027un\u0020utilisateur.",
            "url": "classes/App-Http-Controllers-UserController.html#method_edit_utilisateur"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UserController\u003A\u003Aupdate_utilisateur\u0028\u0029",
            "name": "update_utilisateur",
            "summary": "Met\u0020\u00E0\u0020jour\u0020les\u0020informations\u0020d\u0027un\u0020utilisateur.",
            "url": "classes/App-Http-Controllers-UserController.html#method_update_utilisateur"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UserController\u003A\u003Achange_visibilite\u0028\u0029",
            "name": "change_visibilite",
            "summary": "Change\u0020la\u0020visibilit\u00E9\u0020du\u0020profil\u0020d\u0027un\u0020utilisateur.",
            "url": "classes/App-Http-Controllers-UserController.html#method_change_visibilite"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UserController\u003A\u003Adelete_utilisateur\u0028\u0029",
            "name": "delete_utilisateur",
            "summary": "Supprime\u0020un\u0020utilisateur.",
            "url": "classes/App-Http-Controllers-UserController.html#method_delete_utilisateur"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth",
            "name": "Auth",
            "summary": "",
            "url": "namespaces/app-http-controllers-auth.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-http-controllers.html"
        },                {
            "fqsen": "\\App\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-http.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        }            ]
);
